# SkyCore configuration file
mysql:
  host: 'localhost' # Database host (Default: localhost)
  port: 3306 # Database port (Default: 3306)
  user: '' # Database username (Default: none)
  pass: '' # Database password (Default: none)
  name: 'skycore' # Database name (Default: skycore)